library(targets)

source("functions.R")

tar_option_set(packages = c(
  "tidyverse",
  "patchwork",
  "LaplacesDemon"))

list(
  # Example data sets
  tar_target(dat_uniform1, sim_data(error_type = "uniform", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.1)),
  tar_target(dat_uniform2, sim_data(error_type = "uniform", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.2)),
  tar_target(dat_uniform3, sim_data(error_type = "uniform", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.3)),
  tar_target(dat_uniform4, sim_data(error_type = "uniform", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.4)),
  tar_target(dat_laplace1, sim_data(error_type = "laplace", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.1)),
  tar_target(dat_laplace2, sim_data(error_type = "laplace", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.2)),
  tar_target(dat_laplace3, sim_data(error_type = "laplace", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.3)),
  tar_target(dat_laplace4, sim_data(error_type = "laplace", 
                                   n = 100, 
                                   n_beta = 10, 
                                   n_effect = 3, 
                                   n_response = 2, 
                                   p_zeroes = 0.4)),
  
  
  #### Modeling results ####
  
  # With more observations than covariates
  tar_target(beta_uniform1, fit_n_models(N = 100, 
                                        error_type = "uniform", 
                                        n = 100, 
                                        n_beta = 10, 
                                        n_effect = 3, 
                                        n_response = 2, 
                                        p_zeroes = 0.1)),
  tar_target(beta_laplace1, fit_n_models(N = 100,
                                        error_type = "laplace", 
                                        n = 100, 
                                        n_beta = 10, 
                                        n_effect = 3, 
                                        n_response = 2, 
                                        p_zeroes = 0.1)),
  tar_target(beta_uniform2, fit_n_models(N = 100, 
                                         error_type = "uniform", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.2)),
  tar_target(beta_laplace2, fit_n_models(N = 100,
                                         error_type = "laplace", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.2)),
  tar_target(beta_uniform3, fit_n_models(N = 100, 
                                         error_type = "uniform", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.3)),
  tar_target(beta_laplace3, fit_n_models(N = 100,
                                         error_type = "laplace", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.3)),
  tar_target(beta_uniform4, fit_n_models(N = 100, 
                                         error_type = "uniform", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.4)),
  tar_target(beta_laplace4, fit_n_models(N = 100,
                                         error_type = "laplace", 
                                         n = 100, 
                                         n_beta = 10, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.4)),
  
  
  # With more covariates than observations
  tar_target(beta_uniform1_2, fit_n_models(N = 10, 
                                         error_type = "uniform", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.1)),
  tar_target(beta_laplace1_2, fit_n_models(N = 10,
                                         error_type = "laplace", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.1)),
  tar_target(beta_uniform2_2, fit_n_models(N = 10, 
                                         error_type = "uniform", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.2)),
  tar_target(beta_laplace2_2, fit_n_models(N = 10,
                                         error_type = "laplace", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.2)),
  tar_target(beta_uniform3_2, fit_n_models(N = 10, 
                                         error_type = "uniform", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.3)),
  tar_target(beta_laplace3_2, fit_n_models(N = 10,
                                         error_type = "laplace", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.3)),
  tar_target(beta_uniform4_2, fit_n_models(N = 10, 
                                         error_type = "uniform", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.4)),
  tar_target(beta_laplace4_2, fit_n_models(N = 10,
                                         error_type = "laplace", 
                                         n = 25, 
                                         n_beta = 50, 
                                         n_effect = 3, 
                                         n_response = 2, 
                                         p_zeroes = 0.4))
  
)
